"""
LaTeX Document Processor for Gas Tech Suite
Professional document generation with piping diagrams and technical reports
"""

import os
import subprocess
import tempfile
from typing import Dict, List, Optional, Union, Any
from dataclasses import dataclass
from enum import Enum
import json

class DocumentType(Enum):
    TECHNICAL_REPORT = "technical_report"
    PIPING_DIAGRAM = "piping_diagram"
    COMPLIANCE_CERTIFICATE = "compliance_certificate"
    CALCULATION_REPORT = "calculation_report"
    INSTALLATION_MANUAL = "installation_manual"

class OutputFormat(Enum):
    PDF = "pdf"
    DVI = "dvi"
    PS = "ps"
    HTML = "html"
    LATEX = "latex"

@dataclass
class DocumentSection:
    """Individual document section"""
    title: str
    content: str
    section_level: int  # 1 for chapter, 2 for section, etc.
    include_toc: bool = False
    page_break: bool = False

@dataclass
class PipingDiagramData:
    """Data for piping diagram generation"""
    system_name: str
    pipe_segments: List[Dict]
    appliances: List[Dict]
    fittings: List[Dict]
    calculations: Dict[str, Any]
    scale_factor: float = 1.0

class LatexDocumentProcessor:
    """Advanced LaTeX document processor for gas fitting documents"""
    
    def __init__(self):
        self.templates = self._load_templates()
        self.temp_dir = tempfile.mkdtemp()
        
        # Required LaTeX packages
        self.required_packages = [
            "geometry", "graphicx", "tikz", "pgfplots", "amsmath",
            "amssymb", "booktabs", "array", "multirow", "longtable",
            "fancyhdr", "lastpage", "xcolor", "colortbl", "listings",
            "hyperref", "bookmark", "tocbibind", "natbib"
        ]
    
    def _load_templates(self) -> Dict[str, str]:
        """Load LaTeX templates for different document types"""
        
        base_preamble = r"""
\documentclass[12pt,letterpaper]{article}
\usepackage[top=1in,bottom=1in,left=1in,right=1in]{geometry}
\usepackage{graphicx}
\usepackage{tikz}
\usepackage{pgfplots}
\pgfplotsset{compat=1.17}
\usepackage{amsmath,amssymb}
\usepackage{booktabs}
\usepackage{array}
\usepackage{multirow}
\usepackage{longtable}
\usepackage{fancyhdr}
\usepackage{lastpage}
\usepackage{xcolor}
\usepackage{colortbl}
\usepackage{listings}
\usepackage{hyperref}
\usepackage{bookmark}
\usepackage{tocbibind}
\usepackage{natbib}

\usetikzlibrary{shapes,arrows,positioning,calc,patterns,decorations.pathmorphing}
\hypersetup{
    colorlinks=true,
    linkcolor=blue,
    filecolor=magenta,
    urlcolor=cyan,
    citecolor=blue
}

\lstset{
    basicstyle=\ttfamily\footnotesize,
    breaklines=true,
    frame=single,
    backgroundcolor=\color{gray!10}
}

\pagestyle{fancy}
\fancyhf{}
\rhead{\thepage}
\lhead{Gas Tech Suite}
\chead{Technical Document}
\lfoot{Generated by Gas Tech Suite}
\cfoot{}
\rfoot{Page \thepage\ of \pageref{LastPage}}

\definecolor{gasblue}{RGB}{0,100,200}
\definecolor{gasred}{RGB}{200,50,50}
\definecolor{gasgreen}{RGB}{50,150,50}
\definecolor{gasorange}{RGB}{255,140,0}

\title{Gas Tech Suite Technical Report}
\author{Professional Gas Fitting Software}
\date{\today}
"""
        
        templates = {
            DocumentType.TECHNICAL_REPORT: base_preamble + r"""
\begin{document}
\maketitle
\tableofcontents
\newpage
{content}
\end{document}
""",
            
            DocumentType.PIPING_DIAGRAM: base_preamble + r"""
\begin{document}
\maketitle
{content}
\end{document}
""",
            
            DocumentType.COMPLIANCE_CERTIFICATE: base_preamble + r"""
\begin{document}
\begin{center}
\textbf{\Large GAS TECH SUITE}\\[0.5em]
\textbf{\Large Compliance Certificate}\\[1em]
\end{center}
{content}
\end{document}
""",
            
            DocumentType.CALCULATION_REPORT: base_preamble + r"""
\begin{document}
\maketitle
\tableofcontents
\newpage
{content}
\end{document}
""",
            
            DocumentType.INSTALLATION_MANUAL: base_preamble + r"""
\documentclass[12pt,letterpaper]{book}
\usepackage[top=1in,bottom=1in,left=1in,right=1in]{geometry}
\usepackage{graphicx}
\usepackage{tikz}
\usepackage{amsmath,amssymb}
\usepackage{booktabs}
\usepackage{hyperref}

\title{Gas Tech Suite Installation Manual}
\author{Professional Gas Fitting Guide}
\date{\today}

\begin{document}
\frontmatter
\maketitle
\tableofcontents
\mainmatter
{content}
\end{document}
"""
        }
        
        return templates
    
    def create_section(self, title: str, content: str, level: int = 1, 
                      page_break: bool = False) -> str:
        """Create LaTeX section"""
        
        section_commands = {
            1: "\\chapter{%s}",
            2: "\\section{%s}",
            3: "\\subsection{%s}",
            4: "\\subsubsection{%s}",
            5: "\\paragraph{%s}"
        }
        
        section_cmd = section_commands.get(level, "\\subsection{%s}")
        latex_section = f"{section_cmd % title}\n\n{content}\n\n"
        
        if page_break:
            latex_section = f"\\newpage\n{latex_section}"
        
        return latex_section
    
    def create_table(self, data: List[List[str]], headers: List[str], 
                    caption: str = "", label: str = "") -> str:
        """Create LaTeX table"""
        
        # Determine column alignment
        col_spec = "l" * len(headers)
        
        latex_table = f"""
\\begin{{table}}[h]
\\centering
\\caption{{{caption}}}
\\label{{{label}}}
\\begin{{tabular}}{{{col_spec}}}
\\toprule
{ " & ".join(headers)} \\\\
\\midrule
"""
        
        for row in data:
            latex_table += " & ".join(str(cell) for cell in row) + " \\\\\n"
        
        latex_table += """\\bottomrule
\\end{tabular}
\\end{table}
"""
        
        return latex_table
    
    def create_equation(self, equation: str, label: str = "") -> str:
        """Create LaTeX equation"""
        
        if label:
            return f"\\begin{{equation}}\\label{{{label}}}\n{equation}\n\\end{{equation}}\n"
        else:
            return f"\\[{equation}\\]\n"
    
    def create_piping_diagram(self, diagram_data: PipingDiagramData) -> str:
        """Create TikZ piping diagram"""
        
        latex_code = f"""
\\section{{Piping System Diagram: {diagram_data.system_name}}}

\\begin{{center}}
\\begin{{tikzpicture}}[scale={diagram_data.scale_factor}]
% Define styles
\\tikzstyle{{pipe}} = [draw,thick,rectangle,minimum height=8pt,fill=gray!20]
\\tikzstyle{{appliance}} = [draw,thick,rectangle,minimum width=1cm,minimum height=1cm,fill=gasblue!20]
\\tikzstyle{{fitting}} = [draw,circle,minimum size=6pt,fill=gasorange!20]
\\tikzstyle{{flowarrow}} = [->,thick,gasgreen]

% Draw pipe segments
"""
        
        # Generate pipe segments
        for i, segment in enumerate(diagram_data.pipe_segments):
            x_start = segment.get('x_start', 0)
            y_start = segment.get('y_start', i * 2)
            x_end = segment.get('x_end', 10)
            y_end = segment.get('y_end', i * 2)
            
            pipe_size = segment.get('size', '1"')
            
            latex_code += f"""
% Pipe segment {i+1}
\\draw[pipe,minimum width={x_end-x_start}cm] ({x_start},{y_start}) rectangle ({x_end},{y_end}+0.2);
\\node[above] at ({(x_start+x_end)/2},{y_start}+0.3) {{Pipe {i+1} - {pipe_size}}};
"""
        
        # Add appliances
        for i, appliance in enumerate(diagram_data.appliances):
            x_pos = appliance.get('x_pos', 12)
            y_pos = appliance.get('y_pos', i * 2)
            name = appliance.get('name', f'Appliance {i+1}')
            
            latex_code += f"""
% Appliance {i+1}
\\node[appliance] (app{i}) at ({x_pos},{y_pos}) {{{name}}};
"""
        
        # Add fittings
        for i, fitting in enumerate(diagram_data.fittings):
            x_pos = fitting.get('x_pos', 0)
            y_pos = fitting.get('y_pos', 0)
            fitting_type = fitting.get('type', 'tee')
            
            latex_code += f"""
% Fitting {i+1}
\\node[fitting] at ({x_pos},{y_pos}) {{}};
\\node[below] at ({x_pos},{y_pos}-0.3) {{{fitting_type}}};
"""
        
        # Add flow arrows
        latex_code += """
% Flow direction arrows
\\draw[flowarrow] (0,1) -- (11,1);
\\node[above,gasgreen] at (5.5,1.3) {Gas Flow Direction};
"""
        
        # Add calculations summary
        if diagram_data.calculations:
            latex_code += "\\end{tikzpicture}\n\\end{center}\n\n"
            latex_code += "\\subsection{Calculations Summary}\n\n"
            
            for key, value in diagram_data.calculations.items():
                if isinstance(value, (int, float)):
                    latex_code += f"\\textbf{{{key.replace('_', ' ').title()}:}} {value:,.2f}\n\n"
                else:
                    latex_code += f"\\textbf{{{key.replace('_', ' ').title()}:}} {value}\n\n"
        else:
            latex_code += "\n\\end{tikzpicture}\n\\end{center}\n\n"
        
        return latex_code
    
    def create_calculation_report(self, calculations: Dict[str, Any], 
                                title: str = "Calculation Report") -> str:
        """Create calculation report with equations and results"""
        
        latex_content = f"\\section{{{title}}}\n\n"
        
        # Add calculations with equations
        for calc_name, calc_data in calculations.items():
            latex_content += f"\\subsection{{{calc_name.replace('_', ' ').title()}}}\n\n"
            
            if isinstance(calc_data, dict):
                if 'equation' in calc_data:
                    latex_content += self.create_equation(
                        calc_data['equation'], 
                        f"eq:{calc_name.lower()}"
                    )
                    latex_content += f"{calc_data.get('description', '')}\n\n"
                
                if 'results' in calc_data:
                    latex_content += "\\textbf{Results:}\n\n"
                    latex_content += "\\begin{itemize}\n"
                    for result_name, result_value in calc_data['results'].items():
                        if isinstance(result_value, (int, float)):
                            latex_content += f"\\item {result_name.replace('_', ' ').title()}: {result_value:,.4f}\n"
                        else:
                            latex_content += f"\\item {result_name.replace('_', ' ').title()}: {result_value}\n"
                    latex_content += "\\end{itemize}\n\n"
                
                if 'table_data' in calc_data:
                    table_data = calc_data['table_data']
                    if 'headers' in table_data and 'rows' in table_data:
                        latex_content += self.create_table(
                            table_data['rows'], 
                            table_data['headers'],
                            f"{calc_name} Results"
                        )
            else:
                latex_content += f"{calc_data}\n\n"
        
        return latex_content
    
    def generate_document(self, doc_type: DocumentType, sections: List[DocumentSection],
                         metadata: Dict[str, Any] = None) -> str:
        """Generate complete LaTeX document"""
        
        template = self.templates[doc_type]
        
        # Build content
        content = ""
        for section in sections:
            content += self.create_section(
                section.title, 
                section.content, 
                section.section_level,
                section.page_break
            )
        
        # Replace placeholder in template
        latex_document = template.replace("{content}", content)
        
        # Add custom metadata if provided
        if metadata:
            if 'title' in metadata:
                latex_document = latex_document.replace(
                    "\\title{Gas Tech Suite Technical Report}",
                    f"\\title{{{metadata['title']}}}"
                )
            if 'author' in metadata:
                latex_document = latex_document.replace(
                    "\\author{Professional Gas Fitting Software}",
                    f"\\author{{{metadata['author']}}}"
                )
        
        return latex_document
    
    def compile_document(self, latex_code: str, output_format: OutputFormat = OutputFormat.PDF,
                        output_filename: str = "gas_tech_document") -> Dict[str, Any]:
        """Compile LaTeX document to specified format"""
        
        # Create temporary files
        tex_file = os.path.join(self.temp_dir, f"{output_filename}.tex")
        
        # Write LaTeX code to file
        with open(tex_file, 'w', encoding='utf-8') as f:
            f.write(latex_code)
        
        try:
            # Compile using pdflatex
            if output_format == OutputFormat.PDF:
                result = subprocess.run(
                    ['pdflatex', '-interaction=nonstopmode', '-output-directory', self.temp_dir, tex_file],
                    capture_output=True, text=True, cwd=self.temp_dir
                )
            elif output_format == OutputFormat.DVI:
                result = subprocess.run(
                    ['latex', '-interaction=nonstopmode', '-output-directory', self.temp_dir, tex_file],
                    capture_output=True, text=True, cwd=self.temp_dir
                )
            elif output_format == OutputFormat.PS:
                # First compile to DVI, then convert to PS
                self.compile_document(latex_code, OutputFormat.DVI, output_filename)
                dvi_file = os.path.join(self.temp_dir, f"{output_filename}.dvi")
                result = subprocess.run(
                    ['dvips', '-o', os.path.join(self.temp_dir, f"{output_filename}.ps"), dvi_file],
                    capture_output=True, text=True, cwd=self.temp_dir
                )
            
            # Check compilation result
            if result.returncode == 0:
                # Get output file path
                extension = output_format.value
                output_file = os.path.join(self.temp_dir, f"{output_filename}.{extension}")
                
                if os.path.exists(output_file):
                    with open(output_file, 'rb') as f:
                        file_content = f.read()
                    
                    return {
                        'success': True,
                        'content': file_content,
                        'output_file': output_file,
                        'format': output_format.value,
                        'compilation_log': result.stdout
                    }
                else:
                    return {
                        'success': False,
                        'error': f"Output file not found: {output_file}",
                        'compilation_log': result.stdout + result.stderr
                    }
            else:
                return {
                    'success': False,
                    'error': f"LaTeX compilation failed: {result.stderr}",
                    'compilation_log': result.stdout + result.stderr
                }
        
        except subprocess.CalledProcessError as e:
            return {
                'success': False,
                'error': f"Compilation error: {str(e)}",
                'compilation_log': str(e)
            }
        except FileNotFoundError:
            return {
                'success': False,
                'error': "LaTeX compiler not found. Please install TeX Live or MiKTeX.",
                'compilation_log': ""
            }
    
    def export_to_latex(self, latex_code: str, filename: str) -> str:
        """Export LaTeX code to file"""
        
        output_file = os.path.join(self.temp_dir, f"{filename}.tex")
        
        with open(output_file, 'w', encoding='utf-8') as f:
            f.write(latex_code)
        
        return output_file
    
    def create_compliance_certificate(self, system_data: Dict[str, Any], 
                                    inspection_date: str, inspector: str) -> str:
        """Create compliance certificate document"""
        
        content = f"""
\\section{{System Information}}
\\begin{{itemize}}
\\item System Name: {system_data.get('name', 'N/A')}
\\item Standard: {system_data.get('standard', 'N/A')}
\\item Installation Date: {system_data.get('installation_date', 'N/A')}
\\item Location: {system_data.get('location', 'N/A')}
\\end{{itemize}}

\\section{{Compliance Verification}}
\\begin{{itemize}}
\\item Inspection Date: {inspection_date}
\\item Inspector: {inspector}
\\item Compliance Status: {system_data.get('compliance_status', 'PENDING')}
\\end{{itemize}}

\\section{{Technical Specifications}}
{system_data.get('technical_specs', 'Not provided')}

\\section{{Requirements Met}}
{system_data.get('requirements_met', 'Not provided')}

\\section{{Notes and Recommendations}}
{system_data.get('notes', 'No additional notes')}
"""
        
        return content

# Demo functions
def demo_latex_processor():
    """Demonstrate LaTeX document processor functionality"""
    processor = LatexDocumentProcessor()
    
    # Create sample calculation report
    calculations = {
        'gas_flow': {
            'equation': 'Q = C \\sqrt{\\frac{(P_1^2 - P_2^2) D^5}{G L T Z}}',
            'description': 'Weymouth equation for gas flow calculation',
            'results': {
                'flow_rate_cfph': 1250.5,
                'pressure_drop_psig': 0.125,
                'velocity_fps': 45.2
            }
        },
        'heat_load': {
            'equation': 'Q = U \\times A \\times \\Delta T',
            'description': 'Basic heat transfer equation',
            'results': {
                'total_heat_loss_btuhr': 85000,
                'heat_loss_per_sqft': 85.5
            }
        }
    }
    
    # Create sections
    sections = [
        DocumentSection("Introduction", "This report contains detailed calculations for gas piping system design.", 1),
        DocumentSection("Calculations", processor.create_calculation_report(calculations), 2),
        DocumentSection("Conclusion", "All calculations are verified and compliant with applicable standards.", 1)
    ]
    
    # Generate document
    latex_doc = processor.generate_document(
        DocumentType.CALCULATION_REPORT,
        sections,
        {'title': 'Gas Tech Calculation Report', 'author': 'Professional Engineer'}
    )
    
    print("LaTeX Document Processor Demo:")
    print(f"Generated LaTeX document with {len(latex_doc)} characters")
    
    # Try to compile to LaTeX format
    result = processor.compile_document(latex_doc, OutputFormat.LATEX, "demo_report")
    
    if result['success']:
        print("✅ LaTeX compilation successful")
    else:
        print(f"❌ LaTeX compilation failed: {result.get('error', 'Unknown error')}")

if __name__ == "__main__":
    demo_latex_processor()